### PR TITLE
[14.0][MIG] rental_base

### PR DESCRIPTION
**Pull request by chandni299**

### CODE REVIEW

**Comment by chandni299** [comment]
@oca-transbot @oca-travis @OCA-git-bot any idea on why runboat fails here [https://runboat.odoo-community.org/webui/build.html?name=b62886261-c8da-4781-825e-150164f9e036](https://runboat.odoo-community.org/webui/build.html?name=b62886261-c8da-4781-825e-150164f9e036)? It would be very helpful. Thanks!

**Review by marylla — APPROVED** [review]
I made a functional review. It works as expected. :+1: 

**Menus**
* check the existence of rental menus 

**Test procedure**
* create a new storable product that can be rent
* create the related rental service
* create a new sale order of type rental
* add a sale order line and choose the rental service
  * check the adapted form view of sale order line
* add the start and end date of rental
  * check the amount of time that is sold
* confirm the order
  * check outgoing and incoming deliveries and their planned dates
* change the start and / or end date of sale order line (even though it is confirmed) by using button "update times"
  * check the planned dates of outgoing and / or incoming delivery

**Review by yweng8111 — APPROVED** [review]
well done

**Comment by chandni299** [comment]
Thank you for your reviews @marylla @yweng8111 :+1:

**Pull request merged**
