### PR TITLE
[12.0][ADD] rental_timeline

### PR DESCRIPTION
**Pull request by chandni299**

### CODE REVIEW

**Review by douglascstd — CHANGES_REQUESTED** [review]
[FUNCIONAL TEST][**REPROVED**]

How the time line is shown [OK]:
image


When try to select other Filter, a error is presented [NOK]:
image
Error:
image

**Comment by douglascstd** [comment]
It was a great job @chandni299 . 
I can make others funcional tests if you like. Let me know how i could help you in this journey...

**Comment by chandni299** [comment]
Hello @douglascstd, Thank you for your review.
The error is fixed now. You can test it.

**Comment by chandni299** [comment]
Could you please review once again @douglascstd ?

**Review by douglascstd — APPROVED** [review]
[FUNCTIONAL TESTE] APPROVED

Great job.

image

**Comment by marylla** [comment]
@chandni299 Can you check pre-commit please?

**Comment by chandni299** [comment]
Hello @marylla , the error is like
```
Run actions/setup-python@v2
Version 3.9.7 was not found in the local cache
Error: Version 3.9.7 with arch x[6](https://github.com/OCA/vertical-rental/actions/runs/7223272523/job/19681980364?pr=22#step:3:7)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
How can we fix it?

**Comment by marylla** [comment]
@olaf-wagner @chandni299 Can I merge?

**Comment by chandni299** [comment]
> @olaf-wagner @chandni299 Can I merge?

I think yes :)

**Comment by edescalona** [comment]
LGTM

**Pull request merged**
